apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: quotesapiowner
  description: quotes owner
spec:
  type: business-unit
  profile:
    displayName: Quotes API Team
  children:
    - other

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quotesapi
  description: |
    My Example service which has something to do with APIs and database.
  links:
    - title: Website
      url: http://harness.io
  annotations:
    harness.io/pipelines: |
      Build and Deploy: https://app.harness.io/ng/account/IFG41DWvSnaRLOVNB2uesg/module/cd/orgs/default/projects/globalcorp/pipelines/BadApi/pipeline-studio?storeType=INLINE

  tags:
    - globalcorp
spec:
  type: service
  owner: quotesapiowner
  lifecycle: experimental
#  system: yournamehere-system
#  dependsOn:
#    - component:default/yournamehere-service
